#!/usr/bin/env bash
# Summary: List all available pyenv commands
# Usage: pyenv commands [--no-sh|--sh|--vars]

set -e
[ -n "$PYENV_DEBUG" ] && set -x

while test $# -gt 0; do
  arg=$1 && shift
  case $arg in
    # Provide pyenv completions
    --complete) exec printf '%s\n' --sh --no-sh --vars ;;
    --no-sh) exclude_sh=1 ;;
    --sh) only_sh=1 ;;
    # For internal usage
    --vars) print_vars=1 ;;
  esac
done

shopt -s nullglob lastpipe

defaultIFS=$IFS
IFS=$'\n'
declare -A COMMAND_TO_PATH
while read -r base; do
  for cmdpath in "$base"/pyenv-*; do
    COMMAND_TO_PATH[${cmdpath##*/pyenv-}]=$cmdpath
  done
done <<< "${PATH//:/$'\n'}"

declare -a SORTED_COMMANDS SORTED_PATHS
sort -u <<< "${!COMMAND_TO_PATH[*]}" | {
  while read -r cmd; do
    if [[ $cmd == sh-* ]]; then
        (( exclude_sh )) && continue
        [[ -n ${COMMAND_TO_PATH[${cmd#sh-}]} ]] && ! (( only_sh )) && continue
    elif (( only_sh )); then
      continue
    fi
    SORTED_COMMANDS+=("${cmd#sh-}")
    SORTED_PATHS+=("${COMMAND_TO_PATH[$cmd]}")
  done
}

if (( print_vars )); then
  echo "${COMMAND_TO_PATH[*]@A}; ${SORTED_PATHS[*]@A}; ${SORTED_COMMANDS[*]@A}"
else
  echo "${SORTED_COMMANDS[*]}"
fi
IFS=$defaultIFS
