#!/usr/bin/env bash
# Summary: Display the version of pyenv
#
# Displays the version number of this pyenv release, including the
# current revision from git, if available.
#
# The format of the git revision is:
#   <version>-<num_commits>-<git_sha>
# where `num_commits` is the number of commits since `version` was
# tagged.

[ -n "$PYENV_DEBUG" ] && set -x

shopt -s lastpipe

version="1.2.27"
git_revision=""

# in most cases PYENV_ROOT is already resolved by the main pyenv script
git -C "$PYENV_ROOT" describe --tags HEAD 2>/dev/null | {
  read -r revision
  git_revision=${revision#v}
}
echo "pyenv ${git_revision:-$version}"
exit 0
